- client/index.html
- client/src/components/Modal/Modal.jsx
- client/src/components/Popconfirm/Popconfirm.jsx
- client/src/components/Portal/Portal.jsx
- Portal로 Modal 구현
- Popconfirm 구현
- Button 구현 후 Popconfirm 내부 버튼 대체 필요
> [FE] Modal, Popconfirm 구현

- client/src/App.jsx
- client/src/components/PageInput/PageInput.jsx
- client/src/pages/Test.jsx
###공용 인풋 구현 완료
해당 컴포넌트가 사용되는 페이지는 아래와 같습니다.
-로그인, 회원가입
-이메일 비밀번호 닉네임
- 그룹생성 인풋
- 그룹설정
- 그룹타이틀
- 친구초대
- 닉네임 수정
- 비밀번호 변경
> [FE] Page common Input 구현

- client/src/components/Toggle/Toggle.jsx
> [FE] toggle 구현

- client/src/index.css
> index.css Color 수정 및 추가

- client/src/components/Dropdown/Dropdown.jsx
- dropdown 추가 기능 있는 것 / 없는 것 구현
- 사용법은 노션에 추가할 예정
> [FE] dropdown 구현

- client/src/components/Input/AmountInput.jsx
금액 인풋 컴포넌트 구현
- 숫자만 입력 가능하며 천단위별로 콤바로 구분할 수 있도록 구현
> [FE] common Amount Input

- client/src/components/Popconfirm/Popconfirm.jsx
- client/src/feature/Profile/ProfileBottom.jsx
- client/src/feature/Profile/ProfileTop.jsx
- Popconfirm, 마이페이지에 공통 컴포넌트 버튼 적용
- 공통 컴포넌트랑 따로 움직여야하는 버튼은 css 따로 구현했음
> [FE] button 구현된거 기존 컴포넌트에 적용

- server/src/main/java/com/main/server/member/Member.java
- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todo/domain/Todo.java
- server/src/main/java/com/main/server/todo/domain/TodoStatus.java
- server/src/main/java/com/main/server/todo/dto/TodoDto.java
- server/src/main/java/com/main/server/todo/repository/TodoRepository.java
- server/src/main/java/com/main/server/todo/service/TodoService.java
- server/src/main/java/com/main/server/todogroup/Repository/TodoGroupRepository.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroup.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroupMember.java
- server/src/main/java/com/main/server/todogroup/dto/TodoGroupDto.java
- server/src/main/java/com/main/server/todogroup/service/TodoGroupService.java
1. member todo 연관관계 추가
2. todo CRUD
3. todogroup CRUD
> [BE] todo, todogroup CRUD

- server/src/main/java/com/main/server/todogroup/Repository/TodoGroupRepository.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroup.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroupMember.java
- server/src/main/java/com/main/server/todogroup/dto/InvitationTodoGroup.java
- server/src/main/java/com/main/server/todogroup/dto/TodoGroupDto.java
- server/src/main/java/com/main/server/todogroup/service/TodoGroupService.java
> [BE] todogroup 수정

- server/build.gradle
- server/src/main/java/com/main/server/auth/AuthController.java
- server/src/main/java/com/main/server/auth/AuthService.java
- server/src/main/java/com/main/server/member/Member.java
- server/src/main/java/com/main/server/member/MemberController.java
- server/src/main/java/com/main/server/member/MemberRepository.java
- server/src/main/java/com/main/server/member/MemberService.java
- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todo/domain/Todo.java
- server/src/main/java/com/main/server/todogroup/Repository/TodoGroupRepository.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroup.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroupMember.java
- server/src/main/java/com/main/server/todogroup/dto/TodoGroupDto.java
- server/src/main/java/com/main/server/todogroup/service/TodoGroupService.java
> [BE] Pull 충돌 조정

- client/src/components/Input/PageInput.jsx
> [FE] 폰트 사이즈 적용 불가 버그 수정

- client/src/App.jsx
- client/src/components/Header/Header.jsx
- client/vite.config.js
로그아웃 구현 완료
- api 폴더 생성시 api 폴더로 변경 필요
> [FE] 로그아웃 구현 완료

- server/src/main/java/com/main/server/comment/controller/CommentController.java
- server/src/main/java/com/main/server/comment/domain/Comment.java
- server/src/main/java/com/main/server/comment/dto/CommentDto.java
- server/src/main/java/com/main/server/comment/repository/CommentRepository.java
- server/src/main/java/com/main/server/comment/service/CommentService.java
- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todo/service/TodoService.java
> [BE] comment CRUD

- client/src/App.jsx
- client/src/Layout/PagesLayout.jsx
- client/src/components/Header/Header.jsx
페이지 레이아웃 구현 완료
- 헤더 사이드바 백그라운드 고정
> [FE] 레이아웃 구현 완료

- client/src/pages/ErrorPage.jsx
> [FE] fix 돌아가기 라우트 경로 수정

- client/src/components/Header/Header.jsx
로그아웃 버튼 색상 변경
- 취소 버튼
var(--color-blue-03) -> var(--color-red-01)
- 확인 버튼
var(--color-red-01) -> var(--color-blue-03)
헤더 커서 변경
- 기존 헤더 컨테이너에 cursor 되어있던걸 로고로 변경
> [FE] fix 헤더 수정

- client/src/components/Modal/Modal.jsx
> [FE] Modal 복원

- client/src/api/members.api.js
- client/src/components/Dropdown/Dropdown.jsx
- client/src/components/Popconfirm/Popconfirm.jsx
- client/src/feature/Profile/ProfileBottom.jsx
- client/src/feature/Profile/ProfileTop.jsx
- client/src/pages/ProfilePage.jsx
- client/vite.config.js
- 이미지 삭제
- 비밀번호 변경, 닉네임 변경 validation 텍스트 수정
> [FE] 프로필 페이지 API 연결

- client/src/components/Button/ButtonOauth.jsx
- ButtonOauth.jsx => ButtonContainer 수정
> [FE] fix : 버튼간 간격 수정

- server/src/main/java/com/main/server/comment/controller/CommentController.java
- server/src/main/java/com/main/server/comment/dto/CommentDto.java
- server/src/main/java/com/main/server/todo/domain/Todo.java
- server/src/main/java/com/main/server/todo/dto/TodoDto.java
- server/src/main/java/com/main/server/todo/service/TodoService.java
comment, todo response에 todogroupid 추가함
> [BE] comment, todo response 수정

- client/src/components/Button/Button.jsx
<StyledButton
size={size}
onClick={onClick}
fontcolor={fontcolor}
bordercolor={bordercolor}
fontWeight={fontWeight}
backgroundColor={backgroundColor}  /* color 추가해서 사용 */
label={content}
{...restProps}
/>
> [FE] style : Small Button bg-color props 추가 

- client/package-lock.json
- client/package.json
- client/src/components/Input/ModalInput.jsx
- client/src/components/Input/PageInput.jsx
PageInput
- 아이콘 컬러 적용안되는 버그 수정완료
ModalInput
- props.focused 불리언 전달 안되는 부분 수정 완료
> [FE] 인풋 버그 수정

- client/src/components/Input/AmountInput.jsx
- client/src/components/Input/ModalInput.jsx
- client/src/components/Input/PageInput.jsx
Input 
px -> rem 전체 변경
계산인풋
- 퍼블리싱만 하도록 변경
> [FE] fix 인풋 스타일 수정

- server/src/main/java/com/main/server/comment/service/CommentService.java
- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todo/domain/Todo.java
- server/src/main/java/com/main/server/todo/dto/TodoDto.java
- server/src/main/java/com/main/server/todo/repository/TodoRepository.java
- server/src/main/java/com/main/server/todo/service/TodoService.java
- server/src/main/java/com/main/server/todogroup/dto/InvitationTodoGroupDto.java
todo startDate, endDate로 조회 기능 추가
> [BE] todo startDate, endDate 추가

- client/src/feature/Profile/ProfileGroupSetting.jsx
> [FE] PROFILE API 수정

- client/src/api/members.api.js
- client/src/feature/Signup/Signup.jsx
- 이메일, 닉네임 중복에 대한 알림 메세지 추가
- member.api Signup 단순화
> [FE] 이메일, 닉네임 중복 메세지 & api 정리

- client/src/api/auths.api.js
- client/src/components/Header/Header.jsx
- client/src/feature/Login/Login.jsx
> [FE] fix : api 경로 재변경

- client/src/pages/HomePage.jsx
> [FE] fix : component name

- client/package-lock.json
- client/package.json
- client/public/404.html
- client/public/index.html
- client/src/App.jsx
- client/src/api/api.js
- client/src/api/auths.api.js
- client/src/api/ledgergroups.api.js
- client/src/api/members.api.js
- client/src/api/todogroups.api.js
- client/src/main.jsx
- client/src/store/store.count.js
- client/src/store/store.hide.js
- client/src/store/store.location.js
- client/src/store/store.weather.js
> [FE] API URL, 배포 관련 설정

- server/build.gradle
- server/src/main/java/com/main/server/auth/AuthController.java
- server/src/main/java/com/main/server/comment/controller/CommentController.java
- server/src/main/java/com/main/server/labels/controller/CategoryController.java
- server/src/main/java/com/main/server/ledger/controller/LedgerController.java
- server/src/main/java/com/main/server/ledgerGroup/controller/LedgerGroupController.java
- server/src/main/java/com/main/server/member/MemberController.java
- server/src/main/java/com/main/server/security/SecurityConfig.java
- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
HTTP - HTTPS 연동을 위해서 임시로 작성한 코드만 올립니다
> [BE] SecurityConfig

- client/src/api/ledgergroups.api.js
- client/src/feature/Ledger/LedgerGroup.jsx
- client/src/pages/LedgerPage.jsx
- ledger페이지 멤버 추가
- ledger페이지 플로팅 버튼 추가
- 모달 연결
> [FE] ledger페이지 멤버 / 플로팅 버튼 추가

- client/src/App.jsx
- client/src/api/members.api.js
- client/src/components/Header/Header.jsx
- client/src/feature/Profile/ProfileTop.jsx
- client/src/pages/ProfilePage.jsx
- client/src/store/store.userInfo.js
- userInfo store 설정
- Header에서 라우팅시 :id가 아닌 특정 아이디로 이동 => memberId 받아오는 작업 후 수정 필요
> [FE] userInfo store 설정, :id 설정

- client/src/api/ledgergroups.api.js
- client/src/api/todogroups.api.js
- client/src/components/Sidebar/SidbarPoup.jsx
- client/src/components/Sidebar/Sidebar.jsx
- client/src/feature/Ledger/LedgerCalendar/LedgerCalendar.jsx
- 사이드바 그룹 조회 api 연결 및 기존 추가 api 분리
- 그룹 버튼이 일정이상 넘어가면 각사이드바에서 스크롤 처리 되도록 구현
> [FE] 사이드바 api 연결

- client/src/feature/Ledger/LedgerCalendar/LedgerCalendar.jsx
- 가계부 캘린더 가계부 조회 api 연결
- px -> rem 수정
- 캘린더 width 조정 및 가운데 정렬
> [FE] 가계부 캘린더 api 연결

- server/src/main/java/com/main/server/exception/ExceptionCode.java
- server/src/main/java/com/main/server/member/MemberRepository.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroup.java
- server/src/main/java/com/main/server/todogroup/dto/InvitationTodoGroupDto.java
- server/src/main/java/com/main/server/todogroup/service/TodoGroupService.java
> [BE] Todogroup Invitation 기능 구현

- client/src/components/Todo/ModalTodo/ModalContentCreate.jsx
- client/src/components/Todo/ModalTodo/ModalContentEdit.jsx
- client/src/components/Todo/TodoDate.jsx
- client/src/components/Todo/TodoItem.jsx
- client/src/pages/LedgerPage.jsx
- client/src/pages/TodoPage.jsx
- 라우팅 안되는 문제 해결
- TODO 컴포넌트 높이 해결
- TODO NODATE 노출
> [FE]QA 오류 수정

- client/src/components/Button/Button.jsx
- client/src/components/Button/ButtonOauth.jsx
Button backgroundcolor props Warning 해결
> [FE] 공통 버튼 컴포넌트 backgroundcolor props Warning 해결

- client/src/feature/Todo/TodoList.jsx
- client/src/pages/LedgerPage.jsx
> [FE] 라우팅 오류 수정

- server/src/main/java/com/main/server/comment/controller/CommentController.java
- server/src/main/java/com/main/server/comment/dto/CommentDto.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
- server/src/main/java/com/main/server/todogroup/domain/TodoGroup.java
- server/src/main/java/com/main/server/todogroup/dto/InvitationMemberDto.java
- server/src/main/java/com/main/server/todogroup/service/TodoGroupService.java
- comment profile image 부분
- todogroup에 속한 members 부분 profile image
> [BE] comment profile image, todogroup members profile image

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/api/ledgergroups.api.js
- client/src/components/LedgerBook/LedgerBook.jsx
- client/src/components/Modal/Modal.jsx
- client/src/components/Todo/ModalTodo/ModalContentCreate.jsx
- client/src/components/Todo/ModalTodo/ModalContentDetail.jsx
- client/src/components/Todo/ModalTodo/ModalContentEdit.jsx
- client/src/components/Todo/ModalTodo/TodoComment.jsx
- client/src/feature/Ledger/LedgerContent.jsx
- client/src/feature/Main/MainLedger.jsx
- client/src/feature/Main/MainLedgerList.jsx
- client/src/feature/Main/MainTodo.jsx
- client/src/feature/Main/MainTodoList.jsx
- client/src/feature/Profile/ProfileTop.jsx
- client/src/feature/Todo/TodoList.jsx
- client/src/pages/LedgerPage.jsx
- client/src/pages/MainPage.jsx
- client/src/pages/ProfilePage.jsx
- client/src/pages/TodoPage.jsx
- client/src/query/ledgerList.query.js
- client/src/query/ledgergroup.query.js
- client/src/query/todoList.query.js
- client/src/query/todogroup.query.js
- client/src/query/useQueryFn.js
- 로그인 / 비로그인에 따른 라우팅 적용
- 레이아웃 App.jsx에서 관리
- 지금은 토큰 / 유저정보 구현 안되어 있어서 일단 머지는 안하겠습니다
> [FE] 레이아웃 수정

- client/src/components/Header/Header.jsx
- client/src/components/WeatherWidget/HeaderWeatherWidget.jsx
> [FE] 헤더 날씨 위젯 연결

- client/src/components/Sidebar/Sidebar.jsx
> [FE] 사이드바 스타일 수정

- client/src/components/WeatherWidget/WeatherWidget.jsx
- client/src/feature/Home/Detail.jsx
- client/src/feature/Home/Intro.jsx
- client/src/feature/Home/WeatherImage.jsx
- client/src/feature/Ledger/LedgerCalendar/LedgerCalendar.jsx
- client/src/pages/HomePage.jsx
- 배경 이미지 위에 불투명 오버레이 추가
- 하단 스크롤 이미지를 아이콘으로 변경 
- 폰트 사이즈 조정
> [FE] 홈 스타일 수정

- server/src/main/java/com/main/server/config/StaticResourceConfig.java
- server/src/main/resources/application.properties
comment, todogroup members의 profile image 수정
> [BE] comment, todogroup members의 profile image 수정

- client/src/api/ledgergroups.api.js
- client/src/components/Sidebar/Sidebar.jsx
- client/src/feature/Ledger/LedgerCalendar/LedgerCalendar.jsx
- client/src/feature/Ledger/LedgerCalendar/LegerDetailModal/LegerDetailModal.jsx
- client/src/pages/LedgerPage.jsx
- 가계부 상세조회 모달 구현 완료
-  가계부 상세조회 모달 api 연결 완료
- 캘린더 스크롤 삭제
- 그룹ID 프롭스 추가
- 캘린더 소득 지출 총 소득, 총 지출로 표시되도록 수정 완료
> [FE]  가계부 상세조회 모달 연결 완료

- client/src/feature/Ledger/LedgerCalendar/LegerDetailModal/LegerDetailModal.jsx
> [FE] 가계부 상세조회 캐싱처리

- client/src/App.jsx
- client/src/api/ledgergroups.api.js
- client/src/api/todogroups.api.js
- client/src/components/Sidebar/SidbarPoup.jsx
- client/src/components/Sidebar/Sidebar.jsx
- client/src/components/Todo/ModalTodo/ModalContentDetail.jsx
- client/src/components/Todo/ModalTodo/ModalContentEdit.jsx
- client/src/feature/Main/MainTodoList.jsx
- client/src/feature/Profile/ProfileGroupSetting.jsx
- client/src/feature/Profile/ProfileTop.jsx
- client/src/feature/Todo/TodoList.jsx
- client/src/pages/LedgerPage.jsx
- client/src/pages/TodoPage.jsx
- client/src/store/store.mainGroup.js
- client/src/store/store.userInfo.js
- 투두 date Null값 수정 가능
- 투두 페이지 업데이트 수정
> [FE] 투두 업데이트 오류 수정

- client/src/components/Button/Button.jsx
> fix : medium btn bg-props 추가

- client/src/components/Header/Header.jsx
- client/src/components/LedgerBook/LedgerBook.jsx
- client/src/components/Popconfirm/Popconfirm.jsx
- client/src/components/Todo/ModalTodo/ModalContentCreate.jsx
- client/src/components/Todo/ModalTodo/ModalContentDetail.jsx
- client/src/components/Todo/ModalTodo/ModalContentEdit.jsx
- client/src/components/Todo/ModalTodo/TodoComment.jsx
- client/src/feature/Home/Intro.jsx
- client/src/feature/Login/Login.jsx
- client/src/feature/Profile/ProfileBottom.jsx
- client/src/feature/Profile/ProfileTop.jsx
- client/src/feature/Signup/Signup.jsx
- home 페이지 
- 로그인, 회원가입
- Todo, 가계부
- 마이페이지, 회원탈퇴 팝콘
- 로그아웃 팝콘
hover 스타일 추가
> [FE] Fix 버튼 hover 스타일 수정

- server/src/main/java/com/main/server/ledger/controller/LedgerController.java
Reverts codestates-seb/seb44_main_023#191
> Revert "[BE] CORS error"

- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todo/domain/Todo.java
- server/src/main/java/com/main/server/todo/repository/TodoRepository.java
- server/src/main/java/com/main/server/todo/service/TodoService.java
> [BE] NoDate fetch, NoDate get 수정

- client/src/feature/Main/Clock/Clock.jsx
- client/src/pages/MainPage.jsx
- 메인 페이지 HideScreen에 시계 추가
- 상단 날씨 위젯 추가
> [FE] 메인/HideScreen 시계 추가

- client/src/feature/Login/LoginHeader.jsx
- client/src/feature/Signup/SignupHeader.jsx
- 로그인, 회원가입 로고 useNavigate /home 추가
> [FE] 로그인, 회원가입 로고 useNavigate 추가

- client/src/App.jsx
- client/src/api/api.js
- client/src/components/Header/Header.jsx
- client/src/components/Todo/ModalTodo/ModalContentDetail.jsx
- client/src/components/Todo/ModalTodo/TodoComment.jsx
- client/src/feature/Login/Login.jsx
- client/src/feature/Main/MainLedger.jsx
- client/src/feature/Main/MainTodo.jsx
- client/src/pages/ErrorPage.jsx
> [FE] QA 적용

- client/src/api/ledgergroupedit.api.js
- client/src/api/todogroupedit.api.js
- client/src/components/Group/GroupInfo.jsx
- client/src/components/GroupEdit/GroupEdit.jsx
- client/src/feature/GroupEdit/GroupDeleteConfirm.jsx
- client/src/feature/GroupEdit/GroupEditFrame.jsx
- client/src/feature/GroupEdit/GroupEditSave.jsx
- client/src/feature/GroupEdit/MemberListTag.jsx
- client/src/feature/GroupEdit/group.css
- client/src/feature/GroupEdit/isValidEmail.js
- client/src/feature/Ledger/LedgerContent.jsx
- client/src/feature/Todo/TodoList.jsx
- client/src/pages/LedgerPage.jsx
- client/src/pages/TodoPage.jsx
- client/src/store/store.groupEdit.js
- client/src/utils/util.js
- package-lock.json
- 그룹타이틀수정가능
- 그룹삭제가능
----
1개남았을때 삭제시 문제발생
> [FE] 그룹수정버튼구현

- client/src/feature/Ledger/LedgerModal/LedgerCreate/LedgerCategory.jsx
- client/src/feature/Ledger/LedgerModal/LedgerCreate/LedgerPayments.jsx
- api에서 memberId 삭제 후 고정해 뒀던 memberId 1 값을 수정 해주지 않아 어떤 카테고리를 입력 해도 데이터를 넣어줄때 1로 변환되어 들어간거 였음
> [FE] fix : 카테고리 숫자로 나오는 오류 수정

- client/src/App.jsx
- client/src/feature/Login/Login.jsx
> [FE] fix : login

- client/src/feature/Home/WeatherImage.jsx
- client/src/pages/HomePage.jsx
> [FE] 로그인후, 메인숨기기 배경이미지 날씨연동 

- client/src/feature/Home/Detail.jsx
- 홈 스크롤 밀림 버그 수정
- px -> rem 수정
> [FE] 홈 스크롤 밀림 버그 수정

- server/src/main/java/com/main/server/auth/AuthController.java
- server/src/main/java/com/main/server/auth/AuthService.java
- server/src/main/java/com/main/server/auth/dto/AuthDto.java
- server/src/main/java/com/main/server/auth/dto/AuthResponse.java
- server/src/main/java/com/main/server/ledger/controller/LedgerController.java
- server/src/main/java/com/main/server/ledgerGroup/controller/LedgerGroupController.java
- server/src/main/java/com/main/server/ledgerGroup/service/LedgerGroupService.java
- server/src/main/java/com/main/server/ledgerGroup/service/LedgerGroupServiceImpl.java
- server/src/main/java/com/main/server/member/Member.java
- server/src/main/java/com/main/server/member/MemberController.java
- server/src/main/java/com/main/server/member/MemberService.java
- server/src/main/java/com/main/server/security/CorsConfig.java
- server/src/main/java/com/main/server/security/JwtAuthenticationFilter.java
- server/src/main/java/com/main/server/security/JwtAuthorizationFilter.java
- server/src/main/java/com/main/server/todo/controller/TodoController.java
- server/src/main/java/com/main/server/todogroup/controller/TodoGroupController.java
- server/src/main/java/com/main/server/todogroup/service/TodoGroupService.java
> [BE] feat : be-dev 세팅 완료
